#!/usr/bin/env bash
# Generated by: Warp
set -euo pipefail

# Usage:
#   csv_to_txt.sh INPUT_DIR OUTPUT_DIR
#
# INPUT_DIR:  directory tree containing .csv files
# OUTPUT_DIR: directory where .txt files will be written,
#             preserving the structure of INPUT_DIR
#
# Behavior:
# - For every *.csv under INPUT_DIR:
#   - Creates a corresponding .txt under OUTPUT_DIR with the same
#     relative path (but .csv -> .txt)
#   - Replaces commas with spaces
#   - Trims trailing whitespace at the end of each line
# - Does NOT delete or modify the original CSV files.

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 INPUT_DIR OUTPUT_DIR" >&2
  exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"

# Normalize to remove trailing slashes
INPUT_DIR="${INPUT_DIR%/}"
OUTPUT_DIR="${OUTPUT_DIR%/}"

# Validate input directory
if [ ! -d "$INPUT_DIR" ]; then
  echo "Error: INPUT_DIR '$INPUT_DIR' is not a directory" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Walk all CSV files under INPUT_DIR
find "$INPUT_DIR" -type f -name '*.csv' -print0 | while IFS= read -r -d '' f; do
  # Compute path relative to INPUT_DIR
  rel_path="${f#"$INPUT_DIR"/}"

  # Change extension to .txt
  rel_txt="${rel_path%.csv}.txt"

  # Destination file under OUTPUT_DIR
  out_file="$OUTPUT_DIR/$rel_txt"

  # Ensure destination directory exists
  mkdir -p "$(dirname "$out_file")"

  # Convert commas to spaces and trim trailing whitespace on each line
  sed -E 's/,/ /g; s/[[:space:]]+$//' "$f" > "$out_file"

  echo "$out_file"
done
